[project]
name = "rainbowtracker"
version = "0.2.0"
description = "Tracks Position of Bows"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "skyfield>=1.54",
    "ursina>=8.3.0",
]
